/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#2c1600",
        "tertiary": "#745662",
        "on-error-container": "#93000a",
        "surface-container": "#edefe7",
        "surface-container-high": "#e8e9e1",
        "surface-variant": "#e2e3db",
        "surface-dim": "#d9dbd3",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f0f1e9",
        "secondary-fixed": "#e1e6c2",
        "secondary": "#5c6145",
        "on-background": "#1a1c18",
        "on-secondary-fixed": "#1a1d07",
        "on-primary-container": "#5b3912",
        "inverse-surface": "#2f312c",
        "secondary-fixed-dim": "#c5c9a7",
        "surface-tint": "#7d562d",
        "on-surface-variant": "#50453b",
        "background": "#f9faf2",
        "on-primary-fixed-variant": "#623f18",
        "tertiary-fixed": "#ffd8e7",
        "on-tertiary": "#ffffff",
        "outline": "#82756a",
        "surface-container-highest": "#e2e3db",
        "on-secondary-fixed-variant": "#45492f",
        "outline-variant": "#d4c4b7",
        "primary-fixed-dim": "#f0bd8b",
        "inverse-primary": "#f0bd8b",
        "primary-container": "#d4a373",
        "tertiary-fixed-dim": "#e3bccb",
        "surface": "#f9faf2",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#2b141f",
        "secondary-container": "#e1e6c2",
        "on-tertiary-fixed-variant": "#5b3f4b",
        "on-secondary": "#ffffff",
        "surface-bright": "#f9faf2",
        "tertiary-container": "#c8a3b1",
        "on-secondary-container": "#62674a",
        "surface-container-low": "#f3f4ec",
        "on-tertiary-container": "#543944",
        "primary-fixed": "#ffdcbd",
        "primary": "#7d562d",
        "on-surface": "#1a1c18"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "base": "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans"],
        "display-lg": ["EB Garamond"],
        "display-lg-mobile": ["EB Garamond"],
        "headline-sm": ["EB Garamond"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-md": ["EB Garamond"],
        "body-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "display-lg-mobile": ["36px", { "lineHeight": "42px", "fontWeight": "500" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
